language: ruby
sudo: required
rvm:
- 2.3.0
env:
- db = sqlite
script:
- bin/rails db:environment:set RAILS_ENV=test
- bundle exec rake db:test:prepare 
- bundle exec rspec spec/
branches:
    only:
        - master
