language: ruby
sudo: required
rvm:
- 2.3.1
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
env:
- db = sqlite
script:
- bin/rails db:migrate RAILS_ENV=test
- bundle exec rspec spec/
branches:
    only:
        - master
