language: ruby
sudo: required
rvm:
- 2.3.0
env:
- db = sqlite
script:
- bin/rails db:migrate RAILS_ENV=test
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rspec spec/
branches:
    only:
        - master
